apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: jumpstarter-provision-board-ti
spec:
  params:
    - name: jmp-lease-id
      type: string
    - description: Jumpstarter client name to use
      name: client-name
      type: string
    - description: OS image to provision with
      name: image
      type: string
  steps:
    - computeResources: {}
      image: 'quay.io/bzlotnik/ti-driver:latest'
      name: provision
      script: |
        #!/usr/bin/env bash
        set -ex
        set -o pipefail

        jmp client use-config $(params.client-name)
        export JMP_LEASE=$(params.jmp-lease-id)

        jmp client shell -n "$JMP_LEASE" $(params.client-name) << 'ENDCOMMANDS'
        set -e
        j ti flash \
          --kernel J784S4XEVM.flasher.img \
          --dtb k3-j784s4-evm.dtb \
          --os-image $(params.image)

        exit_code=$?
        echo "Exit code: $exit_code"
        exit $exit_code
        ENDCOMMANDS

        EXIT_CODE=$?
        echo "Exit code: ${EXIT_CODE}"
        if [ $EXIT_CODE -ne 0 ]; then
          echo "Error: flash command failed with exit code ${EXIT_CODE}"
          exit $EXIT_CODE
        fi
  workspaces:
    - mountPath: /root/.config/jumpstarter/clients
      name: jumpstarter-client-secret
      readOnly: true
    - mountPath: /workspace
      name: shared-workspace
